"""empty message

Revision ID: 449c9f89bd25
Revises: ffdc0a98111c
Create Date: 2023-01-13 16:15:07.615906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449c9f89bd25'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=False),
    sa.Column('videoUrl', sa.String(length=50), nullable=True),
    sa.Column('fundingGoal', sa.Numeric(), nullable=False),
    sa.Column('startDate', sa.String(length=50), nullable=False),
    sa.Column('endDate', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('risks', sa.String(length=1000), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###