"""empty message

Revision ID: 5a7c6754a8f1
Revises: 983ff3f1cd80
Create Date: 2023-01-13 16:15:58.798868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7c6754a8f1'
down_revision = '983ff3f1cd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('estimatedDelivery', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'pledges', 'rewards', ['rewardId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pledges', type_='foreignkey')
    op.drop_table('rewards')
    # ### end Alembic commands ###
